name: React Native CI/CD

on:
  workflow_dispatch:
jobs:
  android:
    name: Build Android APK
    runs-on: ubuntu-latest  # Use Ubuntu to build Android

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Specify the Node version

      - name: Install dependencies
        run: |
          npm install
          cd android && ./gradlew clean

      - name: Build APK
        run: |
          cd android && ./gradlew assembleRelease

      - name: Upload APK to GitHub artifacts
        uses: actions/upload-artifact@v4
        with:
          name: android-release-apk
          path: android/app/build/outputs/apk/release/app-release.apk
