name: Generate debug APK

on:
  push:
  workflow_dispatch:

jobs:
  apk:
    name: Generate debug APK
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      # Set up JDK 17 (to match Android Gradle plugin requirement)
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      # Clean the project (remove node_modules and android/build)
      - name: Clean project and install dependencies
        run: |
          rm -rf node_modules
          rm -rf android/build
          yarn install --no-frozen-lockfile  # Reinstall dependencies

      # Set up Android SDK
      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          sdk-version: '30.0.3'
          build-tools-version: '30.0.3'
          target-sdk-version: '30'

      # Grant execute permissions to gradlew
      - name: Grant execute permissions to gradlew
        run: chmod +x ./android/gradlew

      # Clean Gradle build
      - name: Clean Gradle build
        run: |
          cd android
          ./gradlew clean

      # Sync Gradle and regenerate autolinking files
      - name: Sync Gradle and regenerate autolinking files
        run: |
          cd android
          ./gradlew clean
          ./gradlew :app:generateAutolinkingPackageList --stacktrace

      # Build debug APK
      - name: Build debug APK
        run: cd android && ./gradlew assembleDebug --stacktrace 

      # Rename APK for output
      - name: Rename APK 
        run:
          mv "./app/build/outputs/apk/debug/app-debug.apk" "./app/build/outputs/apk/debug/${{ env.OUTPUT_NAME }}.apk"
        
      # Upload the APK as an artifact
      - name: Upload debug APK
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.OUTPUT_NAME }}
          path: app/build/outputs/apk/debug/${{ env.OUTPUT_NAME }}.apk
