name: Generate debug APK

on:
  push:
  workflow_dispatch:

jobs:
  apk:
    name: Generate debug APK
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Verify Gradle wrapper exists and is executable
        run: |
          ls -l ./android/gradlew  # Verify that gradlew exists in the android folder
          chmod +x ./android/gradlew  # Ensure gradlew is executable

      - name: Build debug APK
        run: |
          cd android && ./gradlew assembleDebug --stacktrace  # Ensure you're in the android directory

      - name: Rename APK
        run:
          mv "./app/build/outputs/apk/debug/app-debug.apk" "./app/build/outputs/apk/debug/${{ env.OUTPUT_NAME }}.apk"

      - name: Upload debug APK
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.OUTPUT_NAME }}
          path: app/build/outputs/apk/debug/${{ env.OUTPUT_NAME }}.apk
